name: fa_stepper
description: advanced horizontal style of stepper.
version: 0.0.2
author: di phan<dipnv.fs@gmail.com>
homepage: https://github.com/dipnv/flutter_stepper
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
